### ISSUE TITLE
Project is using old interface

### ISSUE THREAD

**Issue by MathijsG** [ricardoper/slim3-skeleton#3]
Slim 3 changed the containerinterface from Interop to psr in later versions of Slim 3 (https://github.com/slimphp/Slim/commit/305e2df322dbb69ecd3f57ff2732f0ba9596aac5).

See: https://stackoverflow.com/questions/37906363/slim-controller-issue-must-be-an-instance-of-containerinterface-instance-of-s

A solution is to alter ControllerAbstract.php and change:

`use Interop\Container\ContainerInterface;`

to:

`use Psr\Container\ContainerInterface;
`

**Comment by ricardoper** [comment]
Fixed, Thanks @MathijsG.
